config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cars
  resources :owners
  resources :dealerships

  root "cars#index"

  get "cars/new", to: 'cars#new'

  get "owners", to: 'owners#index'

  get "owners/new", to: 'owners#new'

  get "dealerships", to: 'dealerships#index'

  get "dealerships/new", to: 'dealerships#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :owner
    belongs_to :dealership
end

app/models/dealership.rb
class Dealership < ApplicationRecord
    has_many :cars
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

    def index
        @car = Car.all
        render :index
    end

    def new
        @owner = Owner.new
        @car = Car.new
        render :new
    end

    def create
        @car = Car.new(car_params)
        if(@car.save)
            redirect_to "/"
        end
    end

    def car_params
        params.require(:car).permit(:make, :model, :year, :color, :engine_size, :body_type, :owner_id, :dealership_id)
    end


    def edit
        @car = Car.find(params[:id].to_i)
        render :edit
    end

    def show
        @car = Car.find(params[:id].to_i)
    end

    def update
        @car = Car.find(params[:id].to_i)
        @car.update(car_params)
    end

    def destroy
        @car = Car.find(params[:id].to_i)
        @car.destroy
        redirect_to(cars_path)
    end

    

end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
    def index
        @dealership = Dealership.all
        render :index
    end

    def new
        @dealership = Dealership.new
        render :new
    end

    def create
        @dealership = Dealership.new(dealership_params)
        if(@dealership.save)
            redirect_to(dealerships_path)
        end
    end

    def dealership_params
        params.require(:dealership).permit(:name, :dealers_name, :car_id)
    end


    def edit
        @dealership = Dealership.find(params[:id].to_i)
        render :edit
    end

    def show
        @dealership = Dealership.find(params[:id].to_i)
    end

    def update
        @dealership = Dealership.find(params[:id].to_i)
        @dealership.update(dealership_params)
    end

    def destroy
        @dealership = Dealership.find(params[:id].to_i)
        @dealership.destroy
        redirect_to(dealerships_path)
    end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

    def index
        @owner = Owner.all
        render :index
    end

    def new
        @owner = Owner.new
        render :new
    end

    def create
        @owner = Owner.new(owner_params)
        if(@owner.save)
            redirect_to(owners_path)
        end
    end

    def owner_params
        params.require(:owner).permit(:name, :age, :email_address, :phone_number)
    end


    def edit
        @owner = Owner.find(params[:id].to_i)
        render :edit
    end

    def show
        @owner = Owner.find(params[:id].to_i)
    end

    def update
        @owner = Owner.find(params[:id].to_i)
        @owner.update(owner_params)
    end

    def destroy
        @owner = Owner.find(params[:id].to_i)
        @owner.destroy
        redirect_to(owners_path)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f|  %>
    <p>
    <%=f.label 'Make'%><br>
    <%=f.text_field :make %>
    </p>
    <p>
    <%=f.label 'Model'%><br>
    <%=f.text_field :model %>
    </p>
    <p>
    <%=f.label 'Year'%><br>
    <%=f.text_field :year %>
    </p>
    <p>
    <%=f.label 'Color'%><br>
    <%=f.text_field :color %>
    </p>
    <p>
    <%=f.label 'Engine Size'%><br>
    <%=f.text_field :engine_size %>
    </p>
    <p>
    <%=f.label 'Body Type'%><br>
    <%=f.text_field :body_type %>
    </p>

    <p>
    <%=f.label :owner %>    
    <%= collection_select :car, :owner_id, Owner.all, :id, :name, prompt: true %>
    </p>
    <%=f.label :dealership %>    
    <%= collection_select :car, :dealership_id, Dealership.all, :id, :name, prompt: true %>
    </p>
    <%=f.submit 'Add' %>
<%end%>

app/views/cars/edit.html.erb
<h1>Edit Page For <%= @car.make %>  <%= @car.model %> </h1>

<%= render 'form', car: @car %>
<%= link_to 'Show', @car, :class => "btn_over"  %>
<%= link_to 'Back', cars_path , :class => "btn_over" %>

app/views/cars/index.html.erb
<h1>Car Page </h1>

<%= link_to 'Add Car to the Inventory', cars_new_path, :class => "btn" %>
<%= link_to 'Go to the Dealerships Page', dealerships_path, :class => "btn" %>
<%= link_to 'Go to the Owners Page', owners_path, :class => "btn" %>



<h2> Did you find all the Cars you need?</h2>

<table class="list2">   
    <thead>
        <th>Make</th>
        <th>Model</th>
        <th>Year</th>
        <th>Color</th>
        <th>Engine Size</th>
        <th>Body Type</th>
        <th>Owner</th>
        
        
        
    </thead>

    <tbody>
        <% @car.each do |car| %>
            <tr>
                <td style="padding:20px"><%= car.make%></td>
                <td><%= car.model %></td>
                <td><%= car.year %></td>
                <td><%= car.color %></td>
                <td><%= car.engine_size %></td>
                <td><%= car.body_type %></td>
                <td><%= car.owner.name %></td>

                <td><%= link_to 'Show', car, :class => "btn" %></td>
                <td><%= link_to 'Edit', edit_car_path(car), :class => "btn" %></td> 
                <td><%= link_to 'Destroy', car, method: :delete, data: {confirm: 'Are you sure?'} , :class => "btn"  %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/cars/new.html.erb
<h1>Add a new Car below</h1>

<%= render 'form', car: @car %>
<%= link_to 'Show', @car, :class => "btn_over"  %>
<%= link_to 'Back', cars_path , :class => "btn_over" %>

app/views/cars/show.html.erb
<h1>Here is your selected Car: <%= @car.make  %> <%= @car.model %> </h1>


<p>
    Make:
    <%= @car.make %>
</p>

<p>
    Model:
    <%= @car.model %>
</p>

<p>
    Year:
    <%= @car.year %>
</p>

<p>
    Color:
    <%= @car.color %>
</p>

<p>
    Engine Size:
    <%= @car.engine_size %>
</p>
<p>
    Body type:
    <%= @car.body_type %>
</p>

<p>
    Owner:
    <%= @car.owner.name %>
</p>


<%=link_to 'Back', cars_path, :class => "btn" %>

app/views/dealerships/_form.html.erb
<%= form_for(@dealership) do |f|  %>
    <p>
    <%=f.label 'Name'%><br>
    <%=f.text_field :name %>
    </p>
    <p>
    <%=f.label 'Dealer'%><br>
    <%=f.text_field :dealers_name %>
    </p>
    <p>
    <%=f.label :car %>    
    <%= collection_select :dealership, :car_id, Car.all, :id, :model, prompt: true %>
    </p>

    <%=f.submit 'Add' %>
<%end%>

app/views/dealerships/edit.html.erb
<h1>Edit Page For <%= @dealership.name %> </h1>

<%= render 'form', dealership: @dealership %>
<%= link_to 'Show', @dealership, :class => "btn_over"  %>
<%= link_to 'Back', dealerships_path , :class => "btn_over" %>

app/views/dealerships/index.html.erb
<h1> Dealership page </h1>

<%= link_to 'Add Dealership to the Inventory', dealerships_new_path, :class => "btn" %>
<%= link_to 'Go to Cars Page', cars_path, :class => "btn" %>
<%= link_to 'Go to Owners Page', owners_path, :class => "btn" %>



<h2> Did you find all the Dealerships you want?</h2>

<table class="list2">   
    <thead>
        <th>Dealership Name</th>
        <th>Dealer</th>
    </thead>

    <tbody>
        <% @dealership.each do |dealership| %>
            <tr>
                <td style="padding:20px"><%= dealership.name%></td>
                <td><%= dealership.dealers_name %></td>
                

                <td><%= link_to 'Show', dealership,  :class => "btn" %></td>
                <td><%= link_to 'Edit', edit_dealership_path(dealership),  :class => "btn" %></td> 
                <td><%= link_to 'Destroy', dealership, method: :delete, data: {confirm: 'Are you sure?'},  :class => "btn"   %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/dealerships/new.html.erb
<h1>Add a new Dealership below</h1>

<%= render 'form', dealership: @dealership %>
<%= link_to 'Show', @dealership, :class => "btn_over"  %>
<%= link_to 'Back', dealerships_path , :class => "btn_over" %>

app/views/dealerships/show.html.erb
<h1>Here is your selected Dealership: <%= @dealership.name %></h1>


<p>
    Dealership Name:
    <%= @dealership.name %>
</p>

<p>
    Dealer:
    <%= @dealership.dealers_name %>
</p>



<%=link_to 'Back', dealerships_path, :class => "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarInventory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f|  %>
    <p>
    <%=f.label 'Name'%><br>
    <%=f.text_field :name %>
    </p>
    <p>
    <%=f.label 'Age'%><br>
    <%=f.text_field :age %>
    </p>
    <p>
    <%=f.label 'Email Address'%><br>
    <%=f.text_field :email_address %>
    </p>
    <p>
    <%=f.label 'Phone Number'%><br>
    <%=f.text_field :phone_number %>
    </p>
    <p>

    <%=f.submit 'Add' %>
<%end%>

app/views/owners/edit.html.erb
<h1>Edit Page For <%= @owner.name %> </h1>

<%= render 'form', owner: @owner %>
<%= link_to 'Show', @owner, :class => "btn_over"  %>
<%= link_to 'Back', owners_path , :class => "btn_over" %>

app/views/owners/index.html.erb
<h1>Owner Page </h1>

<%= link_to 'Add Owner to the Inventory', owners_new_path, :class => "btn" %>
<%= link_to 'Go to the Dealerships Page', dealerships_path, :class => "btn" %>
<%= link_to 'Go to the Cars Page', cars_path, :class => "btn" %>




<h2> Did you find all the Owners you need?</h2>

<table class="list2">   
    <thead>
        <th>Name</th>
        <th>Age</th>
        <th>Email Address</th>
        <th>Phone Number</th>
    </thead>

    <tbody>
        <% @owner.each do |owner| %>
            <tr>
                <td style="padding:20px"><%= owner.name%></td>
                <td><%= owner.age %></td>
                <td><%= owner.email_address%></td>
                <td><%= owner.phone_number %></td>
                
                

                <td><%= link_to 'Show', owner,  :class => "btn" %></td>
                <td><%= link_to 'Edit', edit_owner_path(owner),  :class => "btn" %></td> 
                <td><%= link_to 'Destroy', owner, method: :delete, data: {confirm: 'Are you sure?'} ,  :class => "btn"  %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/owners/new.html.erb
<h1>Add a new Owner below</h1>

<%= render 'form', owner: @owner %>
<%= link_to 'Show', @owner, :class => "btn_over"  %>
<%= link_to 'Back', owners_path , :class => "btn_over" %>

app/views/owners/show.html.erb
<h1>Here is your selected Owner: <%= @owner.name %></h1>


<p>
    Name:
    <%= @owner.name %>
</p>

<p>
    Age:
    <%= @owner.age %>
</p>

<p>
    Email Address:
    <%= @owner.email_address %>
</p>

<p>
    Phone Number:
    <%= @owner.phone_number %>
</p>




<%=link_to 'Back', owners_path, :class => "btn" %>